/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#9b9d9e",
        "surface-container": "#e6e8ea",
        "primary-fixed": "#7b9cff",
        "on-secondary": "#f3f1ff",
        "on-background": "#2c2f30",
        "on-secondary-fixed": "#1c248e",
        "on-surface-variant": "#595c5d",
        "surface-container-highest": "#dadddf",
        "primary-fixed-dim": "#668eff",
        "on-secondary-container": "#323aa2",
        "surface-tint": "#0050d5",
        "on-tertiary": "#ffeef8",
        "on-tertiary-fixed": "#400040",
        "on-error-container": "#570008",
        "surface": "#f5f6f7",
        "inverse-primary": "#618bff",
        "outline": "#757778",
        "primary-dim": "#0045bc",
        "on-primary-container": "#001d5b",
        "surface-container-low": "#eff1f2",
        "error-container": "#fb5151",
        "secondary": "#4850b7",
        "primary-container": "#7b9cff",
        "surface-container-high": "#e0e3e4",
        "secondary-fixed-dim": "#bbbfff",
        "outline-variant": "#abadae",
        "tertiary-dim": "#802d7c",
        "surface-dim": "#d1d5d7",
        "on-surface": "#2c2f30",
        "on-secondary-fixed-variant": "#3c44ab",
        "inverse-surface": "#0c0f10",
        "on-primary": "#f1f2ff",
        "error": "#b31b25",
        "on-tertiary-fixed-variant": "#6d1a6b",
        "secondary-container": "#ccceff",
        "on-tertiary-container": "#620e61",
        "on-primary-fixed-variant": "#00266f",
        "on-primary-fixed": "#000000",
        "tertiary-fixed": "#f897ee",
        "surface-bright": "#f5f6f7",
        "secondary-fixed": "#ccceff",
        "secondary-dim": "#3b43aa",
        "surface-variant": "#dadddf",
        "error-dim": "#9f0519",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed-dim": "#e98adf",
        "primary": "#0050d5",
        "background": "#f5f6f7",
        "tertiary-container": "#f897ee",
        "tertiary": "#8e3a89",
        "on-error": "#ffefee"
      },
      fontFamily: {
        "headline": ["Manrope"],
        "body": ["Manrope"],
        "label": ["Inter"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
